name = "server"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMmQ3MmEyMzUtNmRhMi00MWEyLTljZmItYzU0MWVkYzgzODc4IiwidGVuYW50X2lkIjoiMjcyMTZjZDVmZmM2ZWRiMGI4OTkwNDRjNmQ0M2E1ZWIwMjM2NzRlNzQ3ZDhmZTg1ZTI1MDNhYzE2MDAzYWQzMiIsImludGVybmFsX3NlY3JldCI6IjNlMDc4YTVkLTlkY2ItNDNkMy05ZDBiLTM3ZDU2ZDhmNzhlMyJ9.LMyOIxGov_oSZgvMEWlHy-fcKr7eoVsGvLE4uTZ0zrA"
JWT_SECRET="my-32-character-ultra-secure-and-ultra-long-secret"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""
